### ISSUE TITLE
Missing switches for zone cleaning

### ISSUE THREAD

**Issue by CVHvisuals** [naofireblade/homebridge-neato#36]
Homebridge will not start with v0.6.0

**Comment by naofireblade** [comment]
Can you post your log output?

**Comment by CVHvisuals** [comment]
Thank you for the response. Here is my log. 0.5.2 works fine with same config file.

[7/15/2019, 6:54:02 PM] Loaded config.json with 4 accessories and 5 platforms.
[7/15/2019, 6:54:02 PM] ---
[7/15/2019, 6:54:04 PM] Loaded plugin: homebridge-camera-ffmpeg
[7/15/2019, 6:54:04 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[7/15/2019, 6:54:04 PM] ---
[7/15/2019, 6:54:04 PM] Loaded plugin: homebridge-config-ui-x
[7/15/2019, 6:54:04 PM] Registering platform 'homebridge-config-ui-x.config'
[7/15/2019, 6:54:04 PM] ---
[7/15/2019, 6:54:04 PM] Loaded plugin: homebridge-harmony
[7/15/2019, 6:54:04 PM] Registering platform 'homebridge-harmonyHub.HarmonyHubWebSocket'
[7/15/2019, 6:54:04 PM] ---
[7/15/2019, 6:54:04 PM] Loaded plugin: homebridge-isy-js
[7/15/2019, 6:54:04 PM] Registering platform 'homebridge-isy-js.isy-js'
[7/15/2019, 6:54:04 PM] ---
[7/15/2019, 6:54:04 PM] Loaded plugin: homebridge-magichome
homebridge API version: 2.4
[7/15/2019, 6:54:04 PM] Registering accessory 'homebridge-magichome.MagicHome'
[7/15/2019, 6:54:04 PM] ---
[7/15/2019, 6:54:05 PM] Loaded plugin: homebridge-neato
[7/15/2019, 6:54:05 PM] Registering platform 'homebridge-neato.NeatoVacuumRobot'
[7/15/2019, 6:54:05 PM] ---
[7/15/2019, 6:54:05 PM] Loading 5 platforms...
[7/15/2019, 6:54:05 PM] [isy-js] Initializing isy-js platform...
[7/15/2019, 6:54:05 PM] [Config] Initializing config platform...
[7/15/2019, 6:54:05 PM] [Config] Spawning homebridge-config-ui-x with PID 445
[7/15/2019, 6:54:05 PM] [NeatoVacuumRobot] Initializing NeatoVacuumRobot platform...
[7/15/2019, 6:54:05 PM] [Harmony Hub] Initializing HarmonyHubWebSocket platform...
[7/15/2019, 6:54:05 PM] [Harmony Hub] HarmonyPlatform Init
[7/15/2019, 6:54:05 PM] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
[7/15/2019, 6:54:05 PM] Loading 4 accessories...
[7/15/2019, 6:54:05 PM] [Bar] Initializing MagicHome accessory...
[7/15/2019, 6:54:05 PM] [Studio] Initializing MagicHome accessory...
[7/15/2019, 6:54:05 PM] [Desk] Initializing MagicHome accessory...
[7/15/2019, 6:54:05 PM] [Bed] Initializing MagicHome accessory...
[7/15/2019, 6:54:05 PM] [Harmony Hub] WARNING - configureAccessory - TV accessory added in your bridge from cache, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
[7/15/2019, 6:54:05 PM] [Harmony Hub] DidFinishLaunching
[7/15/2019, 6:54:05 PM] [Harmony Hub] INFO - Loading activities...
[7/15/2019, 6:54:05 PM] FrontCam is running on port 49203.
[7/15/2019, 6:54:05 PM] Please add [FrontCam] manually in Home app. Setup Code: xxx-xx-xxx
[7/15/2019, 6:54:05 PM] Backyard is running on port 49204.
[7/15/2019, 6:54:05 PM] Please add [Backyard] manually in Home app. Setup Code: xxx-xx-xxx
[7/15/2019, 6:54:05 PM] Gate Camera is running on port 49205.
[7/15/2019, 6:54:05 PM] Please add [Gate Camera] manually in Home app. Setup Code: xxx-xx-xxx
[7/15/2019, 6:54:05 PM] Patio is running on port 49206.
[7/15/2019, 6:54:05 PM] Please add [Patio] manually in Home app. Setup Code: xxx-xx-xxx
[7/15/2019, 6:54:05 PM] Garage is running on port 49207.
[7/15/2019, 6:54:05 PM] Please add [Garage] manually in Home app. Setup Code: xxx-xx-xxx
[7/15/2019, 6:54:05 PM] Kitchen is running on port 49208.
[7/15/2019, 6:54:05 PM] Please add [Kitchen] manually in Home app. Setup Code: xxx-xx-xxx
[7/15/2019, 6:54:05 PM] LivingRoom is running on port 49209.
[7/15/2019, 6:54:05 PM] Please add [LivingRoom] manually in Home app. Setup Code: xxx-xx-xxx
[7/15/2019, 6:54:05 PM] StudioCam is running on port 49210.
[7/15/2019, 6:54:05 PM] Please add [StudioCam] manually in Home app. Setup Code: xxx-xx-xxx
[7/15/2019, 6:54:05 PM] Bedroom Cam is running on port 49211.
[7/15/2019, 6:54:05 PM] Please add [Bedroom Cam] manually in Home app. Setup Code: xxx-xx-xxx
[7/15/2019, 6:54:06 PM] [Desk] DEVICE COLOR: 0,0,100
[7/15/2019, 6:54:06 PM] [Bar] DEVICE COLOR: 0,0,100
[7/15/2019, 6:54:06 PM] [Studio] DEVICE COLOR: 0,0,100
[7/15/2019, 6:54:06 PM] [Bed] DEVICE COLOR: 0,0,100
[7/15/2019, 6:54:07 PM] [Harmony Hub] (Harmony Hub)INFO - configuring Main TV Service
[7/15/2019, 6:54:07 PM] [Harmony Hub] (Harmony Hub)WARNING - No main Activity that match config file found, default to first one
[7/15/2019, 6:54:07 PM] [Harmony Hub] (Harmony Hub)INFO - Configuring Main Activity ATV LivingRoom
[7/15/2019, 6:54:07 PM] [Harmony Hub] (Harmony Hub)INFO - Discovered Activity : PowerOff
[0;37m[7/15/2019, 6:54:08 PM] [0m[0;36m[Config][0m [0;33mConsole v4.5.1 is listening on :: port 8080[0m
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'Kitchen Dimmer'...
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'Front Door IN'...
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'Couch Light'...
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'ZW 008 Multilevel Sensor'...
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'Livingroom Fan'...
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'Bedroom Patio'...
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'Bedroom Lamps'...
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'Garage Fan'...
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'Cyclone LED'...
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'Cyclone LED Energy Meter'...
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'Patio LED'...
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'Patio LED Energy Meter'...
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'Garage Door-Sensor'...
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'Garage Door'...
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'ZW 011 Multilevel Sensor'...
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'Bedroom Fan'...
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'ChristmasLights'...
[7/15/2019, 6:54:10 PM] [isy-js] Initializing platform accessory 'Front Door OUT'...
[0;37m[7/15/2019, 6:57:48 PM] [0m[0;36m[Config][0m [0;31mFailed load accessories from Homebridge: Error: connect ECONNREFUSED 127.0.0.1:51826[0m

Thank You,
Chris

**Comment by christianlallo** [comment]
Hello. Thanks for the 6.0 update! I've been waiting for Zone Cleaning.  Unfortunately, I'm having the same issue as the OP.  When 6.0 is installed, homebridge won't start.  I can't seem to get 5.2 re-installed per your instructions, so I can't *absolutely* guarantee that 5.2. is working now, but everything was absolutely fine before the update.

Here's a copy of the log where the plugin started throwing errors:

[7/18/2019, 11:02:48 AM] [NeatoVacuumRobot] Error updating persistent maps: no serial or secret: undefined
[7/18/2019, 11:02:48 AM] [NeatoVacuumRobot] Found robot #1 named "Vincent" with serial "OPS15518-C4F312792730"
[7/18/2019, 11:02:48 AM] [NeatoVacuumRobot] TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/homebridge-neato/index.js:47:25
    at robot.getPersistentMaps (/usr/local/lib/node_modules/homebridge-neato/index.js:90:11)
    at robotRequest (/usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/robot.js:487:13)
    at Robot.getPersistentMaps (/usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/robot.js:376:5)
    at that.robots.forEach (/usr/local/lib/node_modules/homebridge-neato/index.js:87:15)
    at Array.forEach (<anonymous>:null:null)
    at client.getRobots (/usr/local/lib/node_modules/homebridge-neato/index.js:86:23)
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/client.js:42:17)
    at /usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/api.js:31:45
    at process._tickCallback (internal/process/next_tick.js:68:7)

[7/18/2019, 11:02:48 AM] [NeatoVacuumRobot] Successful login but can't connect to your neato robot.
[7/18/2019, 11:02:48 AM] [NeatoVacuumRobot] Found robot #1 named "Vincent" with serial "OPS15518-C4F312792730"
(node:2478) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/homebridge-neato/index.js:47:25
    at client.getRobots (/usr/local/lib/node_modules/homebridge-neato/index.js:74:7)
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/client.js:46:25)
    at /usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/api.js:34:45
    at process._tickCallback (internal/process/next_tick.js:68:7)

(node:2478) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by naofireblade** [comment]
Thanks everybody. I found the bug. After the last PR the plugin no longer works for Neatos without zone cleaning capability. I'm fixing it right now.

**Comment by naofireblade** [comment]
Fixed in v0.6.1

**Comment by christianlallo** [comment]
Hi. Thanks for the quick response.  Unfortunately, I'm still having the same issue. Just some background.  I have 3 robots registered under my Neato account only one of those is a connected BotVac with zone cleaning capability.  That one is called "Vincent" and he is mentioned specifically in the log which I've copied below.  I'm can provide you with any other info/testing you require.  Just let me know.  Thanks!

[7/21/2019, 9:55:35 PM] [NeatoVacuumRobot] Error updating persistent maps: no serial or secret: undefined
[7/21/2019, 9:55:35 PM] [NeatoVacuumRobot] Found robot #1 named "Vincent" with serial "OPS15518-C4F312792730"
[7/21/2019, 9:55:35 PM] [NeatoVacuumRobot] TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/homebridge-neato/index.js:47:37
    at robot.getPersistentMaps (/usr/local/lib/node_modules/homebridge-neato/index.js:87:41)
    at robotRequest (/usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/robot.js:487:13)
    at Robot.getPersistentMaps (/usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/robot.js:376:5)
    at that.robots.forEach (/usr/local/lib/node_modules/homebridge-neato/index.js:84:39)
    at Array.forEach (<anonymous>:null:null)
    at client.getRobots (/usr/local/lib/node_modules/homebridge-neato/index.js:83:41)
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/client.js:42:17)
    at /usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/api.js:31:45
    at process._tickCallback (internal/process/next_tick.js:68:7)

[7/21/2019, 9:55:35 PM] [NeatoVacuumRobot] Successful login but can't connect to your neato robot.
[7/21/2019, 9:55:35 PM] [NeatoVacuumRobot] Found robot #1 named "Vincent" with serial "OPS15518-C4F312792730"
(node:7024) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/homebridge-neato/index.js:47:37
    at client.getRobots (/usr/local/lib/node_modules/homebridge-neato/index.js:73:25)
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/client.js:46:25)
    at /usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/api.js:34:45
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by naofireblade** [comment]
Ok that's strange because I could reproduce the bug and the fix works for me. I will look into this.
@CVHvisuals does the v0.6.1 works for u?

**Comment by CVHvisuals** [comment]
Comfirmed 0.6.1 fixed the issue for me. I have a Neato Botvac Connected that does not have the zone cleaning feature.

**Comment by christianlallo** [comment]
The other botvacs registered to my neato account aren’t connected at all.
Meaning they don’t have Wi-Fi functionality.  I wonder if that could be the
issue?

Sent from my iPhone

On Jul 22, 2019, at 3:37 AM, Arne <notifications@github.com> wrote:

Ok that's strange because I could reproduce the bug and the fix works for
me. I will look into this.
@CVHvisuals <https://github.com/CVHvisuals> does the v0.6.1 works for u?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/naofireblade/homebridge-neato/issues/36?email_source=notifications&email_token=ADYD2VS7OINKZLRKAZTTPT3QAVPSHA5CNFSM4IDSGMTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2PBMSQ#issuecomment-513676874>,
or mute the thread

**Comment by Staphylococcus** [comment]
Not sure if it's the same issue, but it seems like it is. I'm getting this when I'm trying to run homebridge:

```
[7/25/2019, 1:37:22 PM] [NeatoVacuumRobot] Initializing NeatoVacuumRobot platform...
[7/25/2019, 1:37:24 PM] [NeatoVacuumRobot] Found robot #1 named "1st floor vac" with serial `redacted`
[7/25/2019, 1:37:24 PM] [NeatoVacuumRobot] Found robot #2 named "2nd floor vac" with serial `redacted`
[7/25/2019, 1:37:24 PM] [NeatoVacuumRobot] Error updating persistent maps: TypeError: Cannot read property 'forEach' of undefined: undefined
[7/25/2019, 1:37:24 PM] [NeatoVacuumRobot] Found robot #1 named "1st floor vac" with serial `redacted`
[7/25/2019, 1:37:24 PM] [NeatoVacuumRobot] Found robot #2 named "2nd floor vac" with serial `redacted`
(node:2215) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/homebridge-neato/index.js:47:37
    at robot.getPersistentMaps (/usr/local/lib/node_modules/homebridge-neato/index.js:87:41)
    at /usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/robot.js:482:17
    at /usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/api.js:34:45
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2215) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2215) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[7/25/2019, 1:37:25 PM] [NeatoVacuumRobot] error getting boundaries: failed: [object Object]
```

**Comment by mfagerdal** [comment]
Similar issue - homebridge output to systemdaemon..

Jul 30 17:46:00 mfraspZ homebridge[2196]: [2019-7-30 17:46:00] [NeatoVacuumRobot] Initializing NeatoVacuumRobot platform...
Jul 30 17:46:01 mfraspZ homebridge[2196]: [2019-7-30 17:46:01] Loading 2 accessories...
Jul 30 17:46:05 mfraspZ homebridge[2196]: [2019-7-30 17:46:05] [NeatoVacuumRobot] Error updating persistent maps: no serial or secret: undefined
Jul 30 17:46:05 mfraspZ homebridge[2196]: [2019-7-30 17:46:05] [NeatoVacuumRobot] Found robot #1 named "Erik1" with serial "OPS17717-38D26957A0E9"
Jul 30 17:46:05 mfraspZ homebridge[2196]: [2019-7-30 17:46:05] [NeatoVacuumRobot] TypeError: Cannot read property 'forEach' of undefined
Jul 30 17:46:05 mfraspZ homebridge[2196]: at /usr/local/lib/node_modules/homebridge-neato/index.js:47:37
Jul 30 17:46:05 mfraspZ homebridge[2196]: at robot.getPersistentMaps (/usr/local/lib/node_modules/homebridge-neato/index.js:87:41)
Jul 30 17:46:05 mfraspZ homebridge[2196]: at robotRequest (/usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/robot.js:487:13)
Jul 30 17:46:05 mfraspZ homebridge[2196]: at Robot.getPersistentMaps (/usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/robot.js:376:5)
Jul 30 17:46:05 mfraspZ homebridge[2196]: at that.robots.forEach (/usr/local/lib/node_modules/homebridge-neato/index.js:84:39)
Jul 30 17:46:05 mfraspZ homebridge[2196]: at Array.forEach (<anonymous>)
Jul 30 17:46:05 mfraspZ homebridge[2196]: at client.getRobots (/usr/local/lib/node_modules/homebridge-neato/index.js:83:41)
Jul 30 17:46:05 mfraspZ homebridge[2196]: at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/client.js:42:17)
Jul 30 17:46:05 mfraspZ homebridge[2196]: at /usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/api.js:31:45
Jul 30 17:46:05 mfraspZ homebridge[2196]: at processTicksAndRejections (internal/process/task_queues.js:86:5)
Jul 30 17:46:05 mfraspZ homebridge[2196]: [2019-7-30 17:46:05] [NeatoVacuumRobot] Successful login but can't connect to your neato robot.
Jul 30 17:46:05 mfraspZ homebridge[2196]: [2019-7-30 17:46:05] [NeatoVacuumRobot] Found robot #1 named "Erik1" with serial "OPS17717-38D26957A0E9"
Jul 30 17:46:05 mfraspZ homebridge[2196]: (node:2196) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
Jul 30 17:46:05 mfraspZ homebridge[2196]: at /usr/local/lib/node_modules/homebridge-neato/index.js:47:37
Jul 30 17:46:05 mfraspZ homebridge[2196]: at client.getRobots (/usr/local/lib/node_modules/homebridge-neato/index.js:73:25)
Jul 30 17:46:05 mfraspZ homebridge[2196]: at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/client.js:46:25)
Jul 30 17:46:05 mfraspZ homebridge[2196]: at /usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/api.js:34:45
Jul 30 17:46:05 mfraspZ homebridge[2196]: at processTicksAndRejections (internal/process/task_queues.js:86:5)
Jul 30 17:46:05 mfraspZ homebridge[2196]: (node:2196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Jul 30 17:46:05 mfraspZ homebridge[2196]: (node:2196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Jul 30 17:46:06 mfraspZ homebridge[2196]: [2019-7-30 17:46:06] [NeatoVacuumRobot] Error: Request failed with status code 404: null
Jul 30 17:46:06 mfraspZ homebridge[2196]: [2019-7-30 17:46:06] [NeatoVacuumRobot] Error: Request failed with status code 404: null
Jul 30 17:46:06 mfraspZ homebridge[2196]: [2019-7-30 17:46:06] [NeatoVacuumRobot] Found robot #1 named "Erik1" with serial "OPS17717-38D26957A0E9"
Jul 30 17:46:06 mfraspZ homebridge[2196]: [2019-7-30 17:46:06] [NeatoVacuumRobot] Found robot #2 named "Neato" with serial "WTD09213DD-0128430"
Jul 30 17:46:06 mfraspZ homebridge[2196]: [2019-7-30 17:46:06] [NeatoVacuumRobot] no serial or secret: null
Jul 30 17:46:06 mfraspZ homebridge[2196]: [2019-7-30 17:46:06] [NeatoVacuumRobot] Error updating persistent maps: TypeError: Cannot read property 'forEach' of undefined: undefined
Jul 30 17:46:06 mfraspZ homebridge[2196]: [2019-7-30 17:46:06] [NeatoVacuumRobot] Found robot #1 named "Erik1" with serial "OPS17717-38D26957A0E9"
Jul 30 17:46:06 mfraspZ homebridge[2196]: [2019-7-30 17:46:06] [NeatoVacuumRobot] Found robot #2 named "Neato" with serial "WTD09213DD-0128430"
Jul 30 17:46:06 mfraspZ homebridge[2196]: [2019-7-30 17:46:06] [NeatoVacuumRobot] no serial or secret: null
Jul 30 17:46:06 mfraspZ homebridge[2196]: (node:2196) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
Jul 30 17:46:06 mfraspZ homebridge[2196]: at /usr/local/lib/node_modules/homebridge-neato/index.js:47:37
Jul 30 17:46:06 mfraspZ homebridge[2196]: at robot.getPersistentMaps (/usr/local/lib/node_modules/homebridge-neato/index.js:87:41)
Jul 30 17:46:06 mfraspZ homebridge[2196]: at /usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/robot.js:482:17
Jul 30 17:46:06 mfraspZ homebridge[2196]: at /usr/local/lib/node_modules/homebridge-neato/node_modules/node-botvac/lib/api.js:34:45
Jul 30 17:46:06 mfraspZ homebridge[2196]: at processTicksAndRejections (internal/process/task_queues.js:86:5)
Jul 30 17:46:06 mfraspZ homebridge[2196]: (node:2196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
Jul 30 17:46:07 mfraspZ homebridge[2196]: [2019-7-30 17:46:07] [NeatoVacuumRobot] Error: Request failed with status code 404: null
Jul 30 17:46:07 mfraspZ homebridge[2196]: [2019-7-30 17:46:07] [NeatoVacuumRobot] Error: Request failed with status code 404: null

One botvac d5 "Erik1"- connected and working fine. One older , xv-25, "NEATO" -  no internet capability but registered at neato.com.

**Comment by naofireblade** [comment]
@christianlallo @mfagerdal can you test if your problem is fixed with v0.6.2?

**Comment by christianlallo** [comment]
Plugin and homebridge both loaded successfully with no errors!  Thank you!  Haven’t tested zone cleaning feature because I don’t see how to activate it. The plugin only creates one “clean” switch - I’m not sure what the proper behavior is but I would have suspected a clean switch for each zone would be created.

Thanks you and let me know!

**Comment by christianlallo** [comment]
Just a confirmation.  All standard functionality works. Starting a full map cleaning, returning to dock, etc.  But individual clean accessories for each defined zone on my house map are not being created.  Only one clean accessory is being created. I've attached screenshots of my house map along with the homekit room where my D7 lives.  On interesting observation is that the clean accessory doesn't have the name of the D7 - Vincent - while the other accessories do.

Thanks for the hard work and sorry for the trouble!  

![IMG_90B266587D0E-1](https://user-images.githubusercontent.com/15744342/62218528-a3fa9080-b37a-11e9-90c6-7af4107d340a.jpeg)

![IMG_DF9093E59A05-1](https://user-images.githubusercontent.com/15744342/62218538-a78e1780-b37a-11e9-8a3f-4d5013ec363a.jpeg)

**Comment by christianlallo** [comment]
Any update on this?

**Comment by naofireblade** [comment]
@Staphylococcus @mfagerdal this should be fixed in v0.6.3
