### ISSUE TITLE
Warnings in homebridge 1.3 because of illegal characteristic values

### ISSUE THREAD

**Issue by DJay-X** [naofireblade/homebridge-neato#61]
@naofireblade I hope you are well.

With Homebridge 1.3.x I noticed the following in the Log...

[20.2.2021, 12:36:57] [homebridge-neato] This plugin generated a warning from the characteristic 'Spot ↔': characteristic was supplied illegal value: number 0 exceeded minimum of 100. See https://git.io/JtMGR for more info.
[20.2.2021, 12:36:57] [homebridge-neato] This plugin generated a warning from the characteristic 'Spot ↕': characteristic was supplied illegal value: number 0 exceeded minimum of 100. See https://git.io/JtMGR for more info.
[20.2.2021, 12:37:58] [homebridge-neato] This plugin generated a warning from the characteristic 'Spot ↔': characteristic was supplied illegal value: number 0 exceeded minimum of 100. See https://git.io/JtMGR for more info.
[20.2.2021, 12:37:58] [homebridge-neato] This plugin generated a warning from the characteristic 'Spot ↕': characteristic was supplied illegal value: number 0 exceeded minimum of 100. See https://git.io/JtMGR for more info.

**Comment by barabba9174** [comment]
Same for me:

[2/22/2021, 4:56:25 PM] [homebridge-neato] This plugin threw an error from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[2/22/2021, 4:56:25 PM] [homebridge-neato] This plugin generated a warning from the characteristic 'Spot ↔': characteristic was supplied illegal value: number 0 exceeded minimum of 100. See https://git.io/JtMGR for more info.
[2/22/2021, 4:56:25 PM] [homebridge-neato] This plugin generated a warning from the characteristic 'Spot ↕': characteristic was supplied illegal value: number 0 exceeded minimum of 100. See https://git.io/JtMGR for more info.
[Home (Netatmo Soggiorno) Netatmo Soggiorno@Home (Netatmo Soggiorno) Netatmo Soggiorno Air Pressure@Atmospheric Pressure] characteristic was supplied illegal value: number 1015.4 exceeded maximum of 255
[2/22/2021, 4:56:26 PM] [homebridge-netatmo] This plugin generated a warning from the characteristic 'Atmospheric Pressure': characteristic was supplied illegal value: number 1015.4 exceeded maximum of 255. See https://git.io/JtMGR for more info.

**Comment by BionicThomas** [comment]
Same here.
Added this to the config as I was anyway only using the different rooms and never spot or the others.
Not a real fix as the underlying issue is not solved, but the error message does not show up anymore.

"hidden": ["dock", "dockstate", "eco", "nogolines", "extracare", "schedule", "find", "spot"]

**Comment by NHMerino** [comment]
I have the same problem. And I believe because of it my eco mode is always on on Homekit and cannot turn it off.

**Comment by jlg89** [comment]
Same issue here. BionicThomas' workaround at least let me get rid of the "Spot" related errors, which cleaned up the log tremendously.

**Comment by Pazekal90** [comment]
Same here

**Comment by naofireblade** [comment]
Fixed in v0.7.3

**Comment by nmbrg** [comment]
Its not fixed. And its also still an issue in 1.4.0.

**Comment by abjeroen** [comment]
not fixed, neato 0.7.3 "2022-2-17 13:00:03] [homebridge-neato] This plugin generated a warning from the characteristic 'Spot ↕': characteristic was supplied illegal value: number 0 exceeded minimum of 100. See https://git.io/JtMGR for more info"
