### ISSUE TITLE
Read handler response errors

### ISSUE THREAD

**Issue by jlg89** [naofireblade/homebridge-neato#62]
Seeing a ton of these in the log:

<pre>
3/16/2021, 4:47:53 PM [HOOBS 3DD1@Vacamoto@Vacamoto Clean@On] The read handler for the characteristic 'On' was slow to respond!
3/16/2021, 4:47:53 PM [HOOBS 3DD1@Vacamoto@Vacamoto Clean@On] The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback!
</pre>

**Comment by naofireblade** [comment]
This looks like the Neato API did not respond. I'm working on a fix.

**Comment by sjaugmented** [comment]
I'm getting this same warning.
`[5/28/2021, 5:37:23 AM] [homebridge-neato] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
`

**Comment by naofireblade** [comment]
Should be fixed in the next version (currently in beta testing)

**Comment by jlg89** [comment]
Not a critical issue, doesn't seem to be breaking anything, but still getting similar errors in HOOBS 4.0.100, Node 14.17.5, Homebridge 1.3.4, homebridge-neato 0.7.3. Seems like "slow to respond" is much less of an error than "didn't respond at all," so I'm not sure why the system is complaining.

```
8/31/2021, 10:53:21 AM HOOBS ERROR [HOOBS 3DD1@Vacamoto@Vacamoto Clean@On] The read handler for the characteristic 'On' was slow to respond!
8/31/2021, 10:56:50 AM HOOBS ERROR [HOOBS 3DD1@Vacamoto@Vacamoto Clean@On] The read handler for the characteristic 'On' was slow to respond!
8/31/2021, 11:01:06 AM HOOBS ERROR [HOOBS 3DD1@Vacamoto@Vacamoto Clean@On] The read handler for the characteristic 'On' was slow to respond!
8/31/2021, 11:18:08 AM HOOBS ERROR [HOOBS 3DD1@Vacamoto@Vacamoto Clean@On] The read handler for the characteristic 'On' was slow to respond!
```
